#!/bin/bash
# Copyright © 2021 Kris Nóva <kris@nivenly.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -E


ALICEPATH="/opt/alice"

if [ ! -d "$ALICEPATH" ]; then
   echo ""
   echo "Unable to find alice project in ${ALICEPATH}!"
   echo ""
   echo "See: github.com/kris-nova/alice"
   echo ""
   exit -1
fi



function help() {
    echo ""
    echo "=========================================================="
    echo "Alice is a Kubernetes management bash tool."
    echo ""
    echo "    author: kris nóva <kris@nivenly.com>"
    echo ""
    echo " [Usage]:  alice <command> <project>"
    echo ""
    echo "      Ex:  alice build nivenly.com"
    echo "      Ex:  alice deploy nivenly.com"
    echo ""
    echo " [Available commands]:"
    echo ""
    echo "    build      build a container locally"
    echo "    buildpush  [build], [push]"
    echo "    deploy     [build], [push], [install]"
    echo "    init       initialize a new alice repository"
    echo "    install    install the manifests in <project>/alice"
    echo "    push       push the container image to the configured repository"
    echo "    run        will search for Alicefile.run and execute"
    echo "    uninstall  uninstall the manifests in <project>/alice"
    echo "=========================================================="
    echo ""
    exit
}

######################################
#
# [Validation]
#
CWD=$PWD
cd $ALICEPATH

if [ -z $1 ];then
    help
fi
CMD=$1

if [ -z "$2" ];then
  P="."
else
  P=$2
fi
if [ "$CMD" = "help" ]; then
    help
fi
if [ "$CMD" = "--help" ];then
    help
fi    
if [ "$P" = "help" ];then
    help
fi
if [ "$P" = "--help" ];then
    help
fi
if [ "$P" = "." ];then
    P=$CWD
fi
if [ "$P" != "$CWD" ];then
  P="$CWD/$P"
fi

######################################
# Debug
function debug(){
  echo "------------------------------"
  echo "CMD       :  $CMD"
  echo "P         :  $P"
  echo "CWD       :  $CWD"
  echo "ALICEPATH :  $ALICEPATH"
  echo "------------------------------"
}
######################################
# Enable/Disable Debug
#debug
######################################



######################################
# [Start]

cd $P
$ALICEPATH/bin/$CMD $P
